Database:
  UserName: root
  Password: 12345678
  Host: 127.0.0.1:3306
  DBName: nowthen2021v3
  Charset: utf8
  MaxIdleConns: 10
  MaxOpenConns: 30

Server:
  RunMode: debug
  HttpPort: 1002
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
